---
- name: Reboot Linux Servers
  hosts: 10.11.2.44
  become: true
  gather_facts: false

  tasks:
    - name: Reboot the server
      reboot:
        msg: "Reboot initiated by AWX"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 10
        post_reboot_delay: 30
        test_command: whoami
