- name: Shutdown Ubuntu Servers
  hosts: all
  become: true
  become_method: sudo
  gather_facts: false

  tasks:
    - name: Shutdown immediately
      command: shutdown -h now
      async: 1
      poll: 0
      ignore_errors: true
