
---
- name: Copy PDF file to eco user Documents
  hosts: 10.11.2.11
  gather_facts: no
  become: yes
  become_method: runas
  become_user: SNUC

  tasks:
    - name: Copy PDF file
      ansible.windows.win_copy:
        src: /home/snuc/Downloads/PiP-CA-3.pdf
        dest: C:\Users\eco\Download\sample.pdf
        remote_src: yes
