---
- name: Shutdown Windows desktop
  hosts: windows
  gather_facts: no
  tasks:
    - name: Shutdown Windows now
      ansible.windows.win_shutdown:
        shutdown_timeout: 0
        msg: "System will shutdown now (AWX Ansible)"
