---
- name: Unblock Internet on Windows
#  hosts: windowsl6
  hosts: 10.11.1.83
  gather_facts: no
  tasks:

    - name: Remove outbound block rule
      community.windows.win_firewall_rule:
        name: "Block_Internet_All"
        state: absent
